# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
- name: EndpointV2
  handler: src/EventHandlers.ts
  events:
  - event: PacketDelivered((uint32,bytes32,uint64) origin, address receiver)
  - event: DefaultReceiveLibrarySet(uint32 eid, address newLib)
  - event: ReceiveLibrarySet(address receiver, uint32 eid, address newLib)
- name: ReceiveUln302
  handler: src/EventHandlers.ts
  events:
  - event: UlnConfigSet(address oapp, uint32 eid, (uint64,uint8,uint8,uint8,address[],address[]) config)
  - event: DefaultUlnConfigsSet((uint32,(uint64,uint8,uint8,uint8,address[],address[]))[] params)
- name: OAppOFT
  handler: src/EventHandlers.ts
  events:
  - event: PeerSet(uint32 eid, bytes32 peer)
  - event: RateLimiterSet(address indexed rateLimiter)
  - event: RateLimitsChanged((uint32,uint256,uint256)[] rateLimitConfigs) # event RateLimitsChanged(tuple(uint32 dstEid, uint256 limit, uint256 window)[] rateLimitConfigs)
networks:
- id: 1
  rpc_url: ${ETHEREUM_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0xc02Ab410f0734EFa3F14628780e6e695156024C2
  - name: OAppOFT
- id: 10
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x3c4962Ff6258dcfCafD23a814237B7d6Eb712063
  - name: OAppOFT
- id: 56
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0xB217266c3A98C8B2709Ee26836C98cf12f6cCEC1
  - name: OAppOFT
- id: 130
  rpc_url: ${UNICHAIN_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x6F475642a6e85809B1c36Fa62763669b1b48DD5B
  - name: ReceiveUln302
    address:
    - 0xe1844c5D63a9543023008D332Bd3d2e6f1FE1043
  - name: OAppOFT
- id: 137
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x1322871e4ab09Bc7f5717189434f97bBD9546e95
  - name: OAppOFT
- id: 324
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0xd07C30aF3Ff30D96BDc9c6044958230Eb797DDBF
  - name: ReceiveUln302
    address:
    - 0x04830f6deCF08Dec9eD6C3fCAD215245B78A59e1
  - name: OAppOFT
- id: 480
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x6F475642a6e85809B1c36Fa62763669b1b48DD5B
  - name: ReceiveUln302
    address:
    - 0xe1844c5D63a9543023008D332Bd3d2e6f1FE1043
  - name: OAppOFT
- id: 999
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x3A73033C0b1407574C76BdBAc67f126f6b4a9AA9
  - name: ReceiveUln302
    address:
    - 0x7cacBe439EaD55fa1c22790330b12835c6884a91
  - name: OAppOFT
- id: 1135
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x6F475642a6e85809B1c36Fa62763669b1b48DD5B
  - name: ReceiveUln302
    address:
    - 0xe1844c5D63a9543023008D332Bd3d2e6f1FE1043
  - name: OAppOFT
- id: 1868
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x4bCb6A963a9563C33569D7A512D35754221F3A19
  - name: ReceiveUln302
    address:
    - 0x364B548d8e6DB7CA84AaAFA54595919eCcF961eA
  - name: OAppOFT
- id: 8453
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0xc70AB6f32772f59fBfc23889Caf4Ba3376C84bAf
  - name: OAppOFT
- id: 34443
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0xc1B621b18187F74c8F6D52a6F709Dd2780C09821
  - name: OAppOFT
- id: 42161
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x7B9E184e07a6EE1aC23eAe0fe8D6Be2f663f05e6
  - name: OAppOFT
- id: 57073
  rpc_url: ${INK_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0xca29f3A6f966Cb2fc0dE625F8f325c0C46dbE958
  - name: ReceiveUln302
    address:
    - 0x473132bb594caEF281c68718F4541f73FE14Dc89
  - name: OAppOFT
- id: 59144
  rpc_url: ${LINEA_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0xE22ED54177CE1148C557de74E4873619e6c6b205
  - name: OAppOFT
- id: 81457
  rpc_url: ${BLAST_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x377530cdA84DFb2673bF4d145DCF0C4D7fdcB5b6
  - name: OAppOFT
- id: 534352
  rpc_url: ${SCROLL_RPC_URL}
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x8363302080e711E0CAb978C081b9e69308d49808
  - name: OAppOFT
- id: 7777777
  start_block: 0
  contracts:
  - name: EndpointV2
    address:
    - 0x1a44076050125825900e736c501f859c50fE728c
  - name: ReceiveUln302
    address:
    - 0x57D9775eE8feC31F1B612a06266f599dA167d211
  - name: OAppOFT
unordered_multichain_mode: true
preload_handlers: true
field_selection:
  transaction_fields:
    - hash
